services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: prompt-engineering-test-harness-db
    environment:
      POSTGRES_DB: prompt_monitor
      POSTGRES_USER: prompt_monitor
      POSTGRES_PASSWORD: prompt_monitor_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prompt_monitor"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Browser (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: prompt-engineering-test-harness-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: prompt-engineering-test-harness-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prompt-engineering-test-harness-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://prompt_monitor:prompt_monitor_password@postgres:5432/prompt_monitor
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/__pycache__
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prompt-engineering-test-harness-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: prompt-engineering-test-harness-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
